spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: pro
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
  rabbitmq:
    host: 10.25.193.180
    port: 18087
    username: wq
    password: wq
    virtual-host: /dev/wq
server:
  port: 8881
eureka:
  client:
    service-url:
      defaultZone: http://root:wangqi@localhost:8761/eureka
management:
  security:
    enabled: false
