spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
  rabbitmq:
    host: localhost
    port: 5672
server:
  port: 8881
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false
