server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    registry-refresh-single-vip-address: false
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  user:
    name: root
    password: wangqi
