eureka:
  client:
    service-url:
      defaultZone: http://root:wangqi@localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
