server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangqi880/SpringcloudConfig.git
          search-paths: respo
          username: wangqi880
          password: wq5426946
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://root:wangqi@localhost:8761/eureka

