eureka:
  client:
    service-url:
      defaultZone: http://root:wangqi@localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true


